<?php

namespace AppBundle\Repository;

/**
 * FoodProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodProductRepository extends \Doctrine\ORM\EntityRepository
{
}
